### ISSUE TITLE
Create Cloud Sites article list for top 10 issues

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/rackspace-how-to#1165] opened 2016-06-29 18:12 UTC
The following list contains the top 10 Cloud Sites issues that we can begin improving documentation around. 

The first step (this issue) is to create a table that contains all of the URLS for the articles that contain references to the following 10 items. The beginning of the list is located here https://one.rackspace.com/display/devdoc/How-To+top+10+list+for+Cloud+Sites.

(The comprehensive list is located in the ws repo here https://github.com/rackerlabs/docs-workstream/blob/master/process-and-outreach/cloud-sites-top-ten.md)

Once the table has been populated, the How-To team will discuss next steps.

1	Sites Security - https://github.com/rackerlabs/rackspace-how-to/issues/1189 -@kylelaffoon		
2	Email Issue - https://github.com/rackerlabs/rackspace-how-to/issues/1192			
3	Account Management - https://github.com/rackerlabs/rackspace-how-to/issues/1193	
4	DNS - https://github.com/rackerlabs/rackspace-how-to/issues/1194				
5	Sites Maintenance - https://github.com/rackerlabs/rackspace-how-to/issues/1195		
6	SSL - https://github.com/rackerlabs/rackspace-how-to/issues/1196					
7	FTP - https://github.com/rackerlabs/rackspace-how-to/issues/1197					
8	Site Down - https://github.com/rackerlabs/rackspace-how-to/issues/1198			
9	Domain Name Mgt - https://github.com/rackerlabs/rackspace-how-to/issues/1199		
10	Database - https://github.com/rackerlabs/rackspace-how-to/issues/1200

**Comment by kylelaffoon** [comment] 2016-07-06 20:55
I have populated the list with findings for all ten topics.

**Comment by DonNateR** [comment] 2016-07-07 16:57
Since this list has been made already, I am closing this issue.

**Comment by kylelaffoon** [comment] 2016-07-07 17:44
Can this be kept open as an umbrella for all the Cloud Sites issues?

-Kyle

**Comment by kylelaffoon** [comment] 2016-07-07 17:53
Renee confirmed we can still reference this for the related items after closing.

**Closed** 2016-07-07 17:53 UTC
