### ISSUE TITLE
Cloud Storage App articles are under wrong category.

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/rackspace-how-to#773] opened 2016-04-15 14:33 UTC
In the Sharepoint content folder, there is series of articles entitled "Cloud Storage App for Microsoft Sharepoint." While these articles do regard Microsoft Sharepoint, Beau Bailey believes that these should not be categorized under the "Cloud Office" banner. 

Beau and I are working on a fix for this issue.

Following is a transcript on our conversation through email: 

That is correct. Our articles are based on our hosted sharepoint offering. I have attached a sheet with the previous article info the I had for my reference if it helps any. 
Beau Bailey
Team Leader

From Nate Archer
Date: Friday, April 15, 2016 at 9:17 AM
To: Rackspace Hosting
Subject: Re: Cloud Office Sharepoint Articles

So anything regarding the Cloud Storage App shouldn’t be under Cloud Office?

From: Beau Bailey 
Date: Friday, April 15, 2016 at 9:05 AM
To: Rackspace Hosting 
Subject: Re: Cloud Office Sharepoint Articles

Hey Nate,

Well the issue is these are the wrong articles not just the wrong title. The sharepoint storage app does not apply to our Cloud Office sharepoint offering at all. If that makes sense. There had to have been some type of mixup here. 
Beau Bailey
Team Leader

beau.bailey

From: Nate Archer 
Date: Friday, April 15, 2016 at 8:55 AM
To: Rackspace Hosting
Subject: Re: Cloud Office Sharepoint Articles

Hey Beau:

Sorry for the delay!

I noticed that there are 7 or so “Cloud Storage App” articles. Did you want these separated from the rest of the Sharepoint articles? Currently, these article preside in the Sharepoint content folder. So we have a couple of options here:

We can rename the articles and keep them in the Sharepoint folder?
We can create a new product for the articles called, “Cloud Storage App”.  Currently, these articles link up to the Sharepoint FAQ. While there is a Cloud Storage App overview page, we would need to create a Storage App FAQ. This would also require a Cloud Storage App logo for the support.rackspace.com/how-to landing page.
We can switch the articles to a different content folder, so they point to a separate URL.
Of all the options, option 2 is the most labor intensive, but we’ve added products before.

Let me know what you want to do.

Regards,

-Nate

From: Beau Bailey
Date: Friday, April 15, 2016 at 8:42 AM
To: Rackspace Hosting
Subject: Re: Cloud Office Sharepoint Articles

Hey Nate,

Any idea where we are at on these articles?

Thanks!

Beau Bailey
Team Leader

From: Nate Archer
Date: Thursday, March 31, 2016 at 7:34 AM
To: Rackspace Hosting 
Subject: Re: Cloud Office Sharepoint Articles

Beau:

Someone on the How-to team can do that for you! Is “Cloud Storage App for Microsoft Sharepoint” the only article that is incorrectly categorized?

Regards,

Nate Archer
Intern II (Information Developer)

From: Beau Bailey 
Date: Wednesday, March 30, 2016 at 5:26 PM
To: how-to
Subject: Cloud Office Sharepoint Articles

Hey Team,

I recently noticed that the Sharepoint Articles for the Cloud Office section are incorrect, after the migration. There contain articles for the "Cloud Storage App for Microsoft Sharepoint”.

How can we get this fixed and have the correct articles relocated?

Thanks!
Beau Bailey
Team Leader

**Comment by ReneeRendon** [comment] 2016-05-18 15:12
Need to investigate this for resolution.

**Comment by kylelaffoon** [comment] 2016-05-27 12:38
Ran search for "Cloud Storage App" in Atom and posted results to https://docs.google.com/a/gapps.rackspace.com/spreadsheets/d/1k5eP6QtohL83rnMkyfvvYsDkKLcDJ2KlShi6csrj3Zk/edit?usp=sharing.

**Comment by stephamon** [comment] 2016-05-27 13:31
@kylelaffoon last time we talked to Beau about it (Nate & I), he said that it wasn't a Rackspace Email thing, and didn't even know what it was or if it still existed. 

Several weeks ago, I tried to reach out to the Cloud Files team (because the body of the articles seem to imply that it's related to Cloud Files) but never got a response.

**Comment by kylelaffoon** [comment] 2016-05-27 14:28
Thanks @stephamon . Did you talk to Melissa or Christopher on the Cloud Files team?

**Comment by stephamon** [comment] 2016-05-27 14:48
@kylelaffoon Oh actually it looks like I never sent that email. It was sitting in my drafts folder. No wonder they never responded!

**Comment by kylelaffoon** [comment] 2016-06-01 16:49
Contacted the Cloud Files team. Was referred to Scott Simpson who stated: "You can put them where you’d like, but we didn’t develop that and we don’t support that in the Storage development org." Reached out to SharePoint Product team on Lync (Javier Barrera, John Ross, Mark Watts, and Randy Drisgill). Javier is researching.

**Comment by kylelaffoon** [comment] 2016-06-01 17:58
Received confirmation from Randy Drisgill and Jonathan Mast (tool developer) that this tool is now EOL. I will retire and redirect these articles.

**Comment by kylelaffoon** [comment] 2016-06-02 14:00
Have redirected all Cloud Storage App specific articles. Will now delete those articles. Also reached out to Beau Bailey on the MS SharePoint Intro page (https://support.rackspace.com/how-to/sharepoint/) that lists the Cloud Storage App overview as a "First Steps" item. I think I change this to point to Get started with Rackspace services for SharePoin (https://support.rackspace.com/how-to/getting-started-with-rackspace-services-for-sharepoint/), but verifying first.

**Comment by kylelaffoon** [comment] 2016-06-02 19:54
Had further discussion with Beau. He is anticipating EOL of SharePoint soon. Provided a list of previous KC information which I pasted into a google sheet at https://docs.google.com/a/gapps.rackspace.com/spreadsheets/d/1fnDzJDej-p0BNR7twFa9hm8Nhna3bmHLgvmeWpAmbkA/edit?usp=sharing 
This ticket will need to stay open until the EOL goes into effect.

**Comment by kylelaffoon** [comment] 2016-06-02 20:31
Opened PR 487 to resubmit the redirects for Cloud Storage App.

**Comment by kylelaffoon** [comment] 2016-06-02 20:34
Check in with Beau Bailey on EOL of SharePoint.  See note 2 comments prior.

**Comment by kylelaffoon** [comment] 2016-06-03 14:53
Completed audit against list at https://docs.google.com/a/gapps.rackspace.com/spreadsheets/d/1fnDzJDej-p0BNR7twFa9hm8Nhna3bmHLgvmeWpAmbkA/edit?usp=sharing.

**Comment by kylelaffoon** [comment] 2016-07-14 20:36
Followed up with Beau today: 
"From: Beau Bailey <beau.bailey@rackspace.com>
Date: Thursday, July 14, 2016 at 3:29 PM
To: Rackspace Hosting <kyle.laffoon@RACKSPACE.COM>
Cc: Cody Jobson <cody.jobson@RACKSPACE.COM>
Subject: Re: SharePoint EOL date

Hey Kyle,
 
Thanks for checking up on that! Our team is still in the process of figuring this out and there have been recent meetings but no hard date has been set as of yet, that I am aware of.
 
I will let you know if I hear anything new. Thanks!
 
Beau Bailey
Support Leader, Cloud Office

beau.bailey@rackspace.com
phone: 210-312-1727
Rackspace.com

 
 
From: Kyle Laffoon <kyle.laffoon@RACKSPACE.COM>
Date: Thursday, July 14, 2016 at 2:34 PM
To: Beau Bailey <beau.bailey@rackspace.com>
Cc: Cody Jobson <cody.jobson@RACKSPACE.COM>
Subject: SharePoint EOL date
 
Hey Beau,
 
Checking back to see if you're heard anything further on the SharePoint EOL. Is there a preliminary date?
 
And, with the pending change in departments for you, who should I bug after?
 
Thanks, 
Kyle"

**Comment by kylelaffoon** [comment] 2016-08-12 18:59
Sent email to Cody Jobson to confirm he is the offical poin of contact now when the SharePoint EOL date is confirmed.

**Comment by kylelaffoon** [comment] 2016-08-15 20:09
Cody replied:
"This was a brief talking point in our meeting today.  We have a tentative stretch date but nothing hard set.  It may be early 2017.  If I hear anything concrete, I will let you guys know!"

**Comment by ReneeRendon** [comment] 2016-09-23 13:41
Cloud Storage App has been resolved.
The Sharepoint EOL is documented in the Cloud Office project, so I am closing this issue.

**Closed** 2016-09-23 13:42 UTC
Labels: blocked, documentation quality, enhancement, q1-2017
