### ISSUE TITLE
On boarding doc suggestion - Add article on setting up cron jobs on parse stack

### ISSUE THREAD

**Issue by kylelaffoon** [rackerlabs/rackspace-how-to#1275] opened 2016-07-22 14:26 UTC
Relates to #1264 
SME: Yesenia Ceja
Issue table: Located on one wiki
Setting up cron jobs on the Parse stack or any stack/server for that matter. I couldn’t find any documentation.

**Comment by kylelaffoon** [comment] 2016-07-22 14:27
Emailed Yesenia to inquire about gathering input on this.

**Comment by kylelaffoon** [comment] 2016-08-04 21:04
Emailed Yesenia a list of Cron Job articles to see if we can use something similar. If not, requested her collected notes.

**Comment by kylelaffoon** [comment] 2016-08-16 14:25
From: Yesenia Ceja <yesenia.ceja@RACKSPACE.COM>
Date: Friday, August 5, 2016 at 12:42 PM
To: Rackspace Hosting <kyle.laffoon@RACKSPACE.COM>
Subject: RE: What we need on your doc suggestion - 6

Hey Kyle,
 
I don’t have the knowledge on setting up cron jobs myself that’s why I was asking for an article but didn’t know I would need to provide the steps. Lol My apologies on that. 
 
There are the articles I gave the customer but I don’t know how that can help with writing a How-To article so may have to scrap the request. 
http://www.thesitewizard.com/general/set-cron-job.shtml
http://askubuntu.com/questions/2368/how-do-i-set-up-a-cron-job
http://www.unixgeeks.org/security/newbie/unix/cron-1.html
 
Thank you,
Yesenia Ceja,
Launch Manager
Phone: (210) 312-4774
Toll free: 1-877-934-0407
https://community.rackspace.com/ 
Restorative | Developer | Empathy | Achiever | Strategic



 
 
From: Kyle Laffoon 
Sent: Thursday, August 04, 2016 3:43 PM
To: Yesenia Ceja
Cc: Tyler Lutz; Nate Archer
Subject: What we need on your doc suggestion - 6
 
(Capturing the items in t email until we can sync up in person.This is 1 of 3)
 
Hi Yesenia,
 
From the list at https://one.rackspace.com/pages/editpage.action?pageId=174901302, we have the following 3 items attributed to you:
 
6. Setting up cron jobs on the Parse stack or any stack/server for that matter. I couldn’t find any documentation.
7. Customer is getting “An SSL error has occurred and a secure connection to the server cannot be made.” - Could we get something on how customers can troubleshoot this error?
8. How-To apply SSL cert to NGINX.
 
 
On 6, I found the following items in the How-To. Most are Cloud Sites. Would your steps resemble any of these?
 
-          https://support.rackspace.com/how-to/cloud-files-faq/
-          https://support.rackspace.com/how-to/cloud-sites-faq/ - How do I schedule a cron job for Cloud Sites?
-          https://support.rackspace.com/how-to/create-a-cron-job-to-back-up-a-cloud-sites-sql-server-database/ - Has basic steps we could start with, if you don’t have notes assembled already.
-          https://support.rackspace.com/how-to/enable-or-disable-a-cloud-sites-scheduled-task-cron-job/ - For beginning and ending steps.
-          https://support.rackspace.com/how-to/how-do-i-schedule-a-cron-job-for-cloud-sites/ 
-          https://support.rackspace.com/how-to/use-cron-jobs-to-backup-cloud-sites-to-cloud-files/   
 
 
I’ll be routing separate emails for numbers 7 and 8.
 
Thanks,
Kyle

**Comment by stephamon** [comment] 2016-08-16 14:54
@ReneeRendon @kylelaffoon So we used to have quite a few articles about setting up cron jobs for various tasks--most of them to do with Cloud Sites--but none of them were Rackspace specific, which is why they weren't migrated. If there's nothing specific to Rackspace about setting up a cron job, is this something that we need? 

Would this be better in Community?

**Comment by stephamon** [comment] 2016-08-22 19:26
So, setting up cron jobs is kind of a universal task on *NIX system. Because it's not Rackspace specific, I've emailed Yesenia and Stuart to see if Community would be a good place for this information.

**Comment by stephamon** [comment] 2016-09-02 13:35
Reached out to Stuart and CC'd Alan about this one.

**Comment by stephamon** [comment] 2016-09-02 15:42
Closing since we're not going to make an article on this. I'll keep working to find a home for it in Community though.

**Closed by stephamon** 2016-09-02 15:42 UTC

**Comment by stephamon** [comment] 2016-09-07 15:15
There is a post already in the community for setting up cron jobs on a cloud server. Yesenia confirmed that it met her needs.
